[package]
name = "polycog"
version = "0.1.0"
edition = "2024"

[dependencies]
# Housekeeping
log = "0.4"
simple_logger = "5"
colored = "3"
thiserror = "2"
anyhow = "1"

# Utilities
hecs = "0.10"
glam = "0.29.0"
clap = "4"

# Rendering
vulkano = { git = "https://github.com/vulkano-rs/vulkano.git", rev = "3b2b6441177491f69111981a86fa998a3bff4abb" }
vulkano-shaders = { git = "https://github.com/vulkano-rs/vulkano.git", rev = "3b2b6441177491f69111981a86fa998a3bff4abb" }
vulkano-taskgraph = { git = "https://github.com/vulkano-rs/vulkano.git", rev = "3b2b6441177491f69111981a86fa998a3bff4abb" }
vulkano-util = { git = "https://github.com/vulkano-rs/vulkano.git", rev = "3b2b6441177491f69111981a86fa998a3bff4abb" }
winit = "0.30"

[build-dependencies]
# Housekeeping
anyhow = "1"
